package com.sparta.devquiz.global.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ResponseCode {

    /**
     *200   OK
     */
    // USER API
    OK(200, "REQUEST SUCCESS"),
    LOGIN(200, "LOGIN SUCCESS"),
    LOGOUT(200, "LOGOUT SUCCESS"),
    GET_MY_INFO(200, "SUCCESS TO GET MY INFORMATION"),
    DELETE_USER(200, "SUCCESS TO DELETE USER"),

    // MYPAGE API
    GET_MY_BOARD_INFO(200, "SUCCESS TO GET MY BOARD"),
    GET_MY_COMMENT(200, "SUCCESS TO GET MY COMMENT"),
    GET_MY_QUIZ(200, "SUCCESS TO GET MY QUIZ"),
    GET_MY_CORRECT_QUIZ(200, "SUCCESS TO GET MY CORRECT QUIZ"),
    GET_MY_FAILED_QUIZ(200, "SUCCESS TO GET MY FAILED QUIZ"),
    GET_MY_PASSED_QUIZ(200, "SUCCESS TO GET MY PASSED QUIZ"),
    GET_MY_GROUP(200, "SUCCESS TO GET MY GROUP"),
    ACCEPT_GROUP_INVITATION(200, "ACCEPT INVITATION"),
    REJECT_GROUP_INVITATION(200, "REJECT INVITATION"),
    GET_MY_RANKING(200, "GET MY RANKING"),

    // QUIZ API
    GET_QUIZ(200, "GET QUIZ"),
    GET_RANDOM_QUIZZES(200, "GET 10 QUIZZES"),
    SUBMIT_QUIZ_ANSWER(200, "SUBMIT QUIZ ANSWER"),

    // BOARD API
    GET_BOARDLIST_INFO(200, "SUCCESS TO GET BOARDLIST"),
    GET_BOARD_INFO(200,"SUCCESS TO GET BOARD"),

    // COMMENT API
    GET_ALL_COMMENT(200, "GET ALL COMMENTS"),

    // POINT API
    GET_MY_POINT(200,"GET MY POINT"),

    // SCORE API
    GET_MY_SCORE(200, "GET MY SCORE"),

    // TEAM API
    GET_GROUP_INFO(200, "GET TEAM INFORMATION"),
    INVITE_GROUP(200, "SUCCESS TO INVITE TEAM"),
    GET_RANKING_INFO_IN_GROUP(200, "SUCCESS TO GET RANKING INFORMATION IN TEAM"),
    GET_MY_RANKING_IN_GROUP(200, "SUCCESS TO GET MY RANKING INFORMATION IN TEAM"),

    // RANK API
    GET_ALL_RANKING(200, "GET ALL RANKING"),
    GET_ALL_GROUP_RANKING(200,"GET TEAM RANKING"),


    /**
     * 201  CREATED
     */
    // USER API
    SIGNUP(201, "SIGN UP"),

    // QUIZ API,
    CREATE_QUIZ(201, "SUCCESS TO CREATE QUIZ"),

    // BOARD API
    CREATE_BOARD(201, "SUCCESS TO CREATE BOARD"),

    // COMMENT API
    CREATE_COMMENT(201, "SUCCESS TO CREATE COMMENT"),
    CREATE_LIKE(201, "SUCCESS TO LIKE COMMENT"),

    // TEAM API
    CREATE_GROUP(201, "SUCCESS TO CREATE TEAM"),

    // POINT API
    SAVE_POINT(201,"SUCCESS TO SAVE POINT"),

    // SCORE API
    SAVE_SCORE(201, "SUCCESS TO VERB SCORE"),


    /**
     * 204  NO CONTENT
     *
     * 기존 RESPONSE CODE 200에서  DATA가 "" 인 것들을 204로 사용
     *
     */
    NO_CONTENT(204, "REQUEST SUCCESS, NO CONTENT"),

    // USER API
    UPDATE_MY_INFO(204, "SUCCESS TO UPDATE MY INFORMATION"),

    // QUIZ API
    UPDATE_QUIZ(204, "SUCCESS TO UPDATE QUIZ"),
    DELETE_QUIZ(204, "SUCCESS TO DELETE QUIZ"),

    // BOARD API
    UPDATE_BOARD(204, "SUCCESS TO UPDATE BOARD"),
    DELETE_BOARD(204,"SUCCESS TO DELETE BOARD"),

    // COMMENT API
    UPDATE_COMMENT(204, "SUCCESS TO UPDATE COMMENT"),
    DELETE_COMMENT(204, "SUCCESS TO DELETE COMMENT"),
    DELETE_LIKE(204, "SUCCESS TO DELETE LIKE"),

    // POINT API
    USE_POINT(204,"SUCCESS TO USE MY POINT"),

    // TEAM API
    UPDATE_GROUP_NAME(204, "SUCCESS TO UPDATE TEAM NAME"),
    CHANGE_GROUP_ADMIN(204, "SUCCESS TO CHANGE TEAM ADMIN"),
    EXPEL_GROUP_MEMBER(204, "SUCCESS TO EXPEL TEAM MEMBER"),
    DELETE_GROUP(204, "SUCCESS TO DELETE TEAM")

    ;

    private final int httpStatus;
    private final String message;
    }
